//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 12:05:55 AM CET 
//


package model.java.vxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Bargeintype.datatype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Bargeintype.datatype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="speech"/>
 *     &lt;enumeration value="hotword"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Bargeintype.datatype")
@XmlEnum
public enum BargeintypeDatatype {

    @XmlEnumValue("speech")
    SPEECH("speech"),
    @XmlEnumValue("hotword")
    HOTWORD("hotword");
    private final String value;

    BargeintypeDatatype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BargeintypeDatatype fromValue(String v) {
        for (BargeintypeDatatype c: BargeintypeDatatype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
