//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 12:05:55 AM CET 
//


package model.java.vxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Fetchhint.datatype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Fetchhint.datatype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="prefetch"/>
 *     &lt;enumeration value="safe"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Fetchhint.datatype")
@XmlEnum
public enum FetchhintDatatype {

    @XmlEnumValue("prefetch")
    PREFETCH("prefetch"),
    @XmlEnumValue("safe")
    SAFE("safe");
    private final String value;

    FetchhintDatatype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FetchhintDatatype fromValue(String v) {
        for (FetchhintDatatype c: FetchhintDatatype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
