//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 12:05:55 AM CET 
//


package model.java.vxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.w3.org/2001/vxml}executable.content" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;attGroup ref="{http://www.w3.org/2001/vxml}RestrictedNamelist.attrib"/>
 *       &lt;attribute name="mode" type="{http://www.w3.org/2001/vxml}FilledMode.datatype" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "filled")
public class Filled {

    @XmlElementRefs({
        @XmlElementRef(name = "log", namespace = "http://www.w3.org/2001/vxml", type = Log.class, required = false),
        @XmlElementRef(name = "submit", namespace = "http://www.w3.org/2001/vxml", type = Submit.class, required = false),
        @XmlElementRef(name = "return", namespace = "http://www.w3.org/2001/vxml", type = Return.class, required = false),
        @XmlElementRef(name = "goto", namespace = "http://www.w3.org/2001/vxml", type = Goto.class, required = false),
        @XmlElementRef(name = "exit", namespace = "http://www.w3.org/2001/vxml", type = Exit.class, required = false),
        @XmlElementRef(name = "disconnect", namespace = "http://www.w3.org/2001/vxml", type = Disconnect.class, required = false),
        @XmlElementRef(name = "assign", namespace = "http://www.w3.org/2001/vxml", type = Assign.class, required = false),
        @XmlElementRef(name = "throw", namespace = "http://www.w3.org/2001/vxml", type = Throw.class, required = false),
        @XmlElementRef(name = "prompt", namespace = "http://www.w3.org/2001/vxml", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "data", namespace = "http://www.w3.org/2001/vxml", type = Data.class, required = false),
        @XmlElementRef(name = "if", namespace = "http://www.w3.org/2001/vxml", type = If.class, required = false),
        @XmlElementRef(name = "value", namespace = "http://www.w3.org/2001/vxml", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "audio", namespace = "http://www.w3.org/2001/vxml", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "var", namespace = "http://www.w3.org/2001/vxml", type = Var.class, required = false),
        @XmlElementRef(name = "clear", namespace = "http://www.w3.org/2001/vxml", type = Clear.class, required = false),
        @XmlElementRef(name = "foreach", namespace = "http://www.w3.org/2001/vxml", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "script", namespace = "http://www.w3.org/2001/vxml", type = Script.class, required = false),
        @XmlElementRef(name = "enumerate", namespace = "http://www.w3.org/2001/vxml", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "reprompt", namespace = "http://www.w3.org/2001/vxml", type = Reprompt.class, required = false)
    })
    @XmlMixed
    protected List<java.lang.Object> content;
    @XmlAttribute(name = "mode")
    protected FilledModeDatatype mode;
    @XmlAttribute(name = "namelist")
    protected List<String> namelist;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Log }
     * {@link Submit }
     * {@link Return }
     * {@link Goto }
     * {@link Exit }
     * {@link Disconnect }
     * {@link Assign }
     * {@link Throw }
     * {@link JAXBElement }{@code <}{@link VxmlSpeak }{@code >}
     * {@link Data }
     * {@link If }
     * {@link JAXBElement }{@code <}{@link Value }{@code >}
     * {@link JAXBElement }{@code <}{@link Audio }{@code >}
     * {@link Var }
     * {@link Clear }
     * {@link JAXBElement }{@code <}{@link ForeachNotInPromptType }{@code >}
     * {@link Script }
     * {@link String }
     * {@link JAXBElement }{@code <}{@link Enumerate }{@code >}
     * {@link Reprompt }
     * 
     * 
     */
    public List<java.lang.Object> getContent() {
        if (content == null) {
            content = new ArrayList<java.lang.Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link FilledModeDatatype }
     *     
     */
    public FilledModeDatatype getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilledModeDatatype }
     *     
     */
    public void setMode(FilledModeDatatype value) {
        this.mode = value;
    }

    /**
     * Gets the value of the namelist property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the namelist property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNamelist().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNamelist() {
        if (namelist == null) {
            namelist = new ArrayList<String>();
        }
        return this.namelist;
    }

}
