//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.05 at 03:42:58 PM CET 
//


package pl.model.java.vxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * extends say-as type by allowing the value element as a child
 * 
 * <p>Java class for say-as complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="say-as">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.w3.org/2001/vxml}say-as">
 *       &lt;redefine>
 *         &lt;complexType name="say-as">
 *           &lt;complexContent>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;attribute name="interpret-as" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *               &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *               &lt;attribute name="detail" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *             &lt;/restriction>
 *           &lt;/complexContent>
 *         &lt;/complexType>
 *       &lt;/redefine>
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.w3.org/2001/vxml}value"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "say-as")
public class SayAs
    extends OriginalSayAs
{


}
