//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.05 at 03:42:58 PM CET 
//

package pl.clinic.vxml.schema.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import pl.clinic.vxml.schema.IdentityVC;
import pl.clinic.vxml.schema.NameVC;
import pl.clinic.vxml.schema.VxmlChild;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.w3.org/2001/vxml}data"/>
 *         &lt;group ref="{http://www.w3.org/2001/vxml}event.handler"/>
 *         &lt;element ref="{http://www.w3.org/2001/vxml}form"/>
 *         &lt;element ref="{http://www.w3.org/2001/vxml}link"/>
 *         &lt;element ref="{http://www.w3.org/2001/vxml}menu"/>
 *         &lt;element ref="{http://www.w3.org/2001/vxml}meta1"/>
 *         &lt;element ref="{http://www.w3.org/2001/vxml}metadata1"/>
 *         &lt;element ref="{http://www.w3.org/2001/vxml}property"/>
 *         &lt;element ref="{http://www.w3.org/2001/vxml}script"/>
 *         &lt;element ref="{http://www.w3.org/2001/vxml}var"/>
 *       &lt;/choice>
 *       &lt;attribute name="application" type="{http://www.w3.org/2001/vxml}URI.datatype" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base"/>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "dataOrCatchOrHelp" })
@XmlRootElement(name = "vxml")
public class Vxml implements VxmlChild {

	@XmlElementRefs({
			@XmlElementRef(name = "script", namespace = "http://www.w3.org/2001/vxml", type = Script.class, required = false),
			@XmlElementRef(name = "catch", namespace = "http://www.w3.org/2001/vxml", type = Catch.class, required = false),
			@XmlElementRef(name = "property", namespace = "http://www.w3.org/2001/vxml", type = Property.class, required = false),
			@XmlElementRef(name = "metadata1", namespace = "http://www.w3.org/2001/vxml", type = Metadata1.class, required = false),
			@XmlElementRef(name = "link", namespace = "http://www.w3.org/2001/vxml", type = Link.class, required = false),
			@XmlElementRef(name = "meta1", namespace = "http://www.w3.org/2001/vxml", type = Meta1.class, required = false),
			@XmlElementRef(name = "error", namespace = "http://www.w3.org/2001/vxml", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "menu", namespace = "http://www.w3.org/2001/vxml", type = Menu.class, required = false),
			@XmlElementRef(name = "var", namespace = "http://www.w3.org/2001/vxml", type = Var.class, required = false),
			@XmlElementRef(name = "nomatch", namespace = "http://www.w3.org/2001/vxml", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "help", namespace = "http://www.w3.org/2001/vxml", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "data", namespace = "http://www.w3.org/2001/vxml", type = Data.class, required = false),
			@XmlElementRef(name = "noinput", namespace = "http://www.w3.org/2001/vxml", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "form", namespace = "http://www.w3.org/2001/vxml", type = Form.class, required = false) })
	protected List<java.lang.Object> dataOrCatchOrHelp;
	@XmlAttribute(name = "application")
	protected String application;
	@XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
	@XmlSchemaType(name = "anyURI")
	protected String base;
	@XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
	protected String lang;
	@XmlAttribute(name = "version", required = true)
	protected String version;

	/**
	 * Gets the value of the dataOrCatchOrHelp property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the dataOrCatchOrHelp property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDataOrCatchOrHelp().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Script }
	 * {@link Catch } {@link Property } {@link Metadata1 } {@link Link }
	 * {@link Meta1 } {@link JAXBElement }{@code <}{@link BasicEventHandler
	 * }{@code >} {@link Menu } {@link Var } {@link JAXBElement
	 * }{@code <}{@link BasicEventHandler }{@code >} {@link JAXBElement
	 * }{@code <}{@link BasicEventHandler }{@code >} {@link Data }
	 * {@link JAXBElement }{@code <}{@link BasicEventHandler }{@code >}
	 * {@link Form }
	 * 
	 * 
	 */
	public List<java.lang.Object> getDataOrCatchOrHelp() {
		if (dataOrCatchOrHelp == null) {
			dataOrCatchOrHelp = new ArrayList<java.lang.Object>();
		}
		return this.dataOrCatchOrHelp;
	}

	/**
	 * Gets the value of the application property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getApplication() {
		return application;
	}

	/**
	 * Sets the value of the application property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setApplication(String value) {
		this.application = value;
	}

	/**
	 * Gets the value of the base property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBase() {
		return base;
	}

	/**
	 * Sets the value of the base property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBase(String value) {
		this.base = value;
	}

	/**
	 * Gets the value of the lang property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLang() {
		return lang;
	}

	/**
	 * Sets the value of the lang property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLang(String value) {
		this.lang = value;
	}

	/**
	 * Gets the value of the version property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVersion(String value) {
		this.version = value;
	}

	@Override
	public List<VxmlChild> getChildrens() {
		List<VxmlChild> list = new ArrayList<VxmlChild>();
		for (java.lang.Object object : getDataOrCatchOrHelp()) {
			if (object instanceof JAXBElement) {
				if (((JAXBElement) object).getValue() instanceof VxmlChild) {
					list.add((VxmlChild) ((JAXBElement) object).getValue());
				}
			} else if (object instanceof VxmlChild) {
			}
		}
		return list;
	}

	@Override
	public NameVC getChildByName(String Name) {
		return null;
	}

	@Override
	public IdentityVC getChildByIdentity(String identity) {
		return null;
	}

}
